Merge plotting tests into mpet-regression-test.yml for accurate coveralls coverage.

diff --git a/.github/workflows/mpet-regression-test.yml b/.github/workflows/mpet-regression-test.yml
--- a/.github/workflows/mpet-regression-test.yml
+++ b/.github/workflows/mpet-regression-test.yml
@@ -50,7 +50,7 @@ jobs:
     - name: run tests for modified branch and get coverage
       run: |
         cd mpet/bin/workdir
-        coverage run --source=../../mpet/ run_tests.py --test_dir ./tests --output_dir ../../bin/workdir/modified > /dev/null
+        coverage run --source=mpet run_tests.py --test_dir=tests --output_dir=modified > /dev/null
 
     - name: upload Coveralls
       env:
@@ -61,5 +61,17 @@ jobs:
 
     - name: Checks test results
       run: |
-        cd mpet/tests
-        pytest --baseDir=ref_outputs --modDir=../bin/workdir/modified compare_tests.py
+        cd mpet/bin/workdir
+        pytest --baseDir=tests/ref_outputs --modDir=modified tests/compare_tests.py
+
+    - name: Check plotting results
+      run: |
+          cd mpet/bin/workdir
+          coverage run --source=mpet -m pytest --baseDir=tests/ref_outputs --modDir=modified tests/plot_data_tests.py
+  
+    - name: upload Coveralls
+      env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      run: |
+          cd mpet/bin/workdir
+          coveralls --service=github || : #Dont fret if if fails
