Add flake8 code style check to regression tests

diff --git a/.github/workflows/mpet-docker-regression-test.yml b/.github/workflows/mpet-docker-regression-test.yml
--- a/.github/workflows/mpet-docker-regression-test.yml
+++ b/.github/workflows/mpet-docker-regression-test.yml
@@ -56,6 +56,10 @@ jobs:
         cd mpet/bin/workdir
         coveralls --service=github || : #Dont fret if if fails
 
+    - name: check code style
+      run: |
+        cd mpet
+        flake8 || :  # Allow failure while still working on style fixes
 
     - name: Checks test results
       run: |
